package nlp.preprocess;

import java.util.HashMap;
import java.util.Map;

public class StopWords {
    private Map<String, Boolean> stopWordsList;

    public StopWords() {
        stopWordsList = new HashMap<>();
        initializeStopWordsList();
    }

    private void initializeStopWordsList() {
        stopWordsList.put("0", true);
        stopWordsList.put("1", true);
        stopWordsList.put("2", true);
        stopWordsList.put("3", true);
        stopWordsList.put("4", true);
        stopWordsList.put("5", true);
        stopWordsList.put("6", true);
        stopWordsList.put("7", true);
        stopWordsList.put("8", true);
        stopWordsList.put("9", true);

        stopWordsList.put("a", true);
        stopWordsList.put("about", true);
        stopWordsList.put("above", true);
        stopWordsList.put("after", true);
        stopWordsList.put("again", true);
        stopWordsList.put("against", true);
        stopWordsList.put("all", true);
        stopWordsList.put("am", true);
        stopWordsList.put("an", true);
        stopWordsList.put("and", true);
        stopWordsList.put("any", true);
        stopWordsList.put("are", true);
        stopWordsList.put("aren't", true);
        stopWordsList.put("as", true);
        stopWordsList.put("at", true);
        stopWordsList.put("be", true);
        stopWordsList.put("because", true);
        stopWordsList.put("been", true);
        stopWordsList.put("before", true);
        stopWordsList.put("being", true);
        stopWordsList.put("below", true);
        stopWordsList.put("between", true);
        stopWordsList.put("both", true);
        stopWordsList.put("but", true);
        stopWordsList.put("by", true);
        stopWordsList.put("can't", true);
        stopWordsList.put("cannot", true);
        stopWordsList.put("could", true);
        stopWordsList.put("couldn't", true);
        stopWordsList.put("did", true);
        stopWordsList.put("didn't", true);
        stopWordsList.put("do", true);
        stopWordsList.put("does", true);
        stopWordsList.put("doesn't", true);
        stopWordsList.put("doing", true);
        stopWordsList.put("don't", true);
        stopWordsList.put("down", true);
        stopWordsList.put("during", true);
        stopWordsList.put("each", true);
        stopWordsList.put("few", true);
        stopWordsList.put("for", true);
        stopWordsList.put("from", true);
        stopWordsList.put("further", true);
        stopWordsList.put("had", true);
        stopWordsList.put("hadn't", true);
        stopWordsList.put("has", true);
        stopWordsList.put("hasn't", true);
        stopWordsList.put("have", true);
        stopWordsList.put("haven't", true);
        stopWordsList.put("having", true);
        stopWordsList.put("he", true);
        stopWordsList.put("he'd", true);
        stopWordsList.put("he'll", true);
        stopWordsList.put("he's", true);
        stopWordsList.put("her", true);
        stopWordsList.put("here", true);
        stopWordsList.put("here's", true);
        stopWordsList.put("hers", true);
        stopWordsList.put("herself", true);
        stopWordsList.put("him", true);
        stopWordsList.put("himself", true);
        stopWordsList.put("his", true);
        stopWordsList.put("how", true);
        stopWordsList.put("how's", true);
        stopWordsList.put("i", true);
        stopWordsList.put("i'd", true);
        stopWordsList.put("i'll", true);
        stopWordsList.put("i'm", true);
        stopWordsList.put("i've", true);
        stopWordsList.put("if", true);
        stopWordsList.put("in", true);
        stopWordsList.put("into", true);
        stopWordsList.put("is", true);
        stopWordsList.put("isn't", true);
        stopWordsList.put("it", true);
        stopWordsList.put("it's", true);
        stopWordsList.put("its", true);
        stopWordsList.put("itself", true);
        stopWordsList.put("let's", true);
        stopWordsList.put("me", true);
        stopWordsList.put("more", true);
        stopWordsList.put("most", true);
        stopWordsList.put("mustn't", true);
        stopWordsList.put("my", true);
        stopWordsList.put("myself", true);
        stopWordsList.put("no", true);
        stopWordsList.put("nor", true);
        stopWordsList.put("not", true);
        stopWordsList.put("of", true);
        stopWordsList.put("off", true);
        stopWordsList.put("on", true);
        stopWordsList.put("once", true);
        stopWordsList.put("only", true);
        stopWordsList.put("or", true);
        stopWordsList.put("other", true);
        stopWordsList.put("ought", true);
        stopWordsList.put("our", true);
        stopWordsList.put("ours ", true);
        stopWordsList.put(" ourselves", true);
        stopWordsList.put("out", true);
        stopWordsList.put("over", true);
        stopWordsList.put("own", true);
        stopWordsList.put("same", true);
        stopWordsList.put("shan't", true);
        stopWordsList.put("she", true);
        stopWordsList.put("she'd", true);
        stopWordsList.put("she'll", true);
        stopWordsList.put("she's", true);
        stopWordsList.put("should", true);
        stopWordsList.put("shouldn't", true);
        stopWordsList.put("so", true);
        stopWordsList.put("some", true);
        stopWordsList.put("say", true);
        stopWordsList.put("said", true);
        stopWordsList.put("such", true);
        stopWordsList.put("than", true);
        stopWordsList.put("that", true);
        stopWordsList.put("that's", true);
        stopWordsList.put("the", true);
        stopWordsList.put("their", true);
        stopWordsList.put("theirs", true);
        stopWordsList.put("them", true);
        stopWordsList.put("themselves", true);
        stopWordsList.put("then", true);
        stopWordsList.put("there", true);
        stopWordsList.put("there's", true);
        stopWordsList.put("these", true);
        stopWordsList.put("they", true);
        stopWordsList.put("they'd", true);
        stopWordsList.put("they'll", true);
        stopWordsList.put("they're", true);
        stopWordsList.put("they've", true);
        stopWordsList.put("this", true);
        stopWordsList.put("those", true);
        stopWordsList.put("through", true);
        stopWordsList.put("to", true);
        stopWordsList.put("too", true);
        stopWordsList.put("under", true);
        stopWordsList.put("until", true);
        stopWordsList.put("up", true);
        stopWordsList.put("very", true);
        stopWordsList.put("was", true);
        stopWordsList.put("wasn't", true);
        stopWordsList.put("we", true);
        stopWordsList.put("we'd", true);
        stopWordsList.put("we'll", true);
        stopWordsList.put("we're", true);
        stopWordsList.put("we've", true);
        stopWordsList.put("were", true);
        stopWordsList.put("weren't", true);
        stopWordsList.put("what", true);
        stopWordsList.put("what's", true);
        stopWordsList.put("when", true);
        stopWordsList.put("when's", true);
        stopWordsList.put("where", true);
        stopWordsList.put("where's", true);
        stopWordsList.put("which", true);
        stopWordsList.put("while", true);
        stopWordsList.put("who", true);
        stopWordsList.put("who's", true);
        stopWordsList.put("whom", true);
        stopWordsList.put("why", true);
        stopWordsList.put("why's", true);
        stopWordsList.put("with", true);
        stopWordsList.put("won't", true);
        stopWordsList.put("would", true);
        stopWordsList.put("wouldn't", true);
        stopWordsList.put("you", true);
        stopWordsList.put("you'd", true);
        stopWordsList.put("you'll", true);
        stopWordsList.put("you're", true);
        stopWordsList.put("you've", true);
        stopWordsList.put("your", true);
        stopWordsList.put("yours", true);
        stopWordsList.put("yourself", true);
        stopWordsList.put("yourselves ", true);
    }

    public boolean isStopWord(String word) {
        return (word.length() == 1 || stopWordsList.containsKey(word));
    }
}
